#! /usr/bin/env bash

CLR_NOR="\x1b[0m"  # back to NORMAL
CLR_BOLD="\x1b[1m" # BOLD text
CLR_RED="\x1b[31m" # RED text
CLR_GRN="\x1b[32m" # GREEN text
CLR_YLW="\x1b[33m" # YELLOW text

export WQ_HOME=`pwd`

echo -e "${CLR_YLW}Checking Pyhton version......${CLR_NOR}"
PYV=`python -c "import sys;t='{v[0]}.{v[1]}'.format(v=list(sys.version_info[:2]));sys.stdout.write(t)";`
if [[ $PYV == 2.7 ]]
then
    alias PY=python3;
    alias PIP=pip3;
    alias NTB=ipython notebook;
fi
if [[ $PYV == 3* ]]
then
    alias PY=python;
    alias PIP=pip;
    alias NTB=ipython notebook;
fi
if (PY -V); then
    echo -e "${CLR_YLW}Pyhton version checked......${CLR_NOR}${CLR_GRN}OK${CLR_NOR}"
else
    echo -e "${CLR_YLW}Pyhton version checked......${CLR_NOR}${CLR_RED}Failed${CLR_NOR}"
    exit -1
fi

echo -e "${CLR_YLW}Setting Pyhton path to user local......${CLR_NOR}${CLR_GRN}Done${CLR_NOR}"
export PYTHONPATH=$WQ_HOME/.py/lib/python$PYV/site-packages/:$WQ_HOME/src:$WQ_HOME/scripts

if (PY -c "import virtualenv as venv"); then
    echo -e "${CLR_YLW}Checking virtualenv......${CLR_NOR}${CLR_GRN}OK${CLR_NOR}"
else
    echo -e "${CLR_YLW}Checking virtualenv......${CLR_NOR}${CLR_RED}Failed${CLR_NOR}"
    echo -e "${CLR_YLW}Reinstalling virtualenv......${CLR_NOR}"
    PIP uninstall virtualenv
    PIP install virtualenv
    echo -e "${CLR_YLW}Reinstalling virtualenv......${CLR_NOR}${CLR_GRN}Done${CLR_NOR}"
fi

if (PY bin/env.py); then
    source .py/bin/activate

    echo -e "${CLR_YLW}Installing numpy......${CLR_NOR}"
    PIP install numpy==1.9.1
    echo -e "${CLR_YLW}Installing numpy......${CLR_NOR}${CLR_GRN}OK${CLR_NOR}"

    echo -e "${CLR_YLW}Installing scipy......${CLR_NOR}"
    PIP install scipy==0.14.0
    echo -e "${CLR_YLW}Installing scipy......${CLR_NOR}${CLR_GRN}OK${CLR_NOR}"

    echo -e "${CLR_YLW}Installing ipython......${CLR_NOR}"
    PIP install ipython==2.3.0
    echo -e "${CLR_YLW}Installing ipython......${CLR_NOR}${CLR_GRN}OK${CLR_NOR}"

    echo -e "${CLR_YLW}Installing dependencies......${CLR_NOR}"
    PIP install -r requirements.txt
    echo -e "${CLR_YLW}Installing dependencies......${CLR_NOR}${CLR_GRN}OK${CLR_NOR}"

    if [[ $WQ_ENV ]]
    then
        echo -e "${CLR_YLW}Current environment: ${CLR_NOR}${CLR_RED}$WQ_ENV${CLR_NOR}"
    else
        export WQ_ENV="dev"
        echo -e "${CLR_YLW}Current environment: ${CLR_NOR}${CLR_RED}$WQ_ENV${CLR_NOR}"
    fi

    export PATH="$PATH:${WQ_HOME}/bin/"
    NTB
fi
